"""Persona library for crisis simulation templates."""

PERSONA_LIBRARY = [
    {"type": "twitter_skeptic", "name": "Twitter Skeptic", "platform": "Twitter/X", "influence_score": 6.0,
     "description": "A skeptical tech enthusiast who questions everything",
     "traits": {"skepticism": 0.9, "outrage_prone": 0.6, "snark": 0.8},
     "biases": ["anti_corporate", "anti_hype", "pro_transparency"]},
    {"type": "twitter_fanboy", "name": "Twitter Fanboy", "platform": "Twitter/X", "influence_score": 4.0,
     "description": "An enthusiastic supporter who defends the brand",
     "traits": {"enthusiasm": 0.9, "skepticism": 0.1, "loyalty": 0.8},
     "biases": ["pro_innovation", "brand_loyal"]},
    {"type": "twitter_activist", "name": "Twitter Activist", "platform": "Twitter/X", "influence_score": 7.5,
     "description": "A social justice warrior who amplifies outrage",
     "traits": {"outrage_prone": 0.95, "moral_certainty": 0.9, "amplification": 0.9},
     "biases": ["social_justice", "anti_corporate", "pro_accountability"]},
    {"type": "twitter_journalist", "name": "Twitter Journalist", "platform": "Twitter/X", "influence_score": 8.5,
     "description": "A tech reporter looking for the next big story",
     "traits": {"skepticism": 0.7, "fact_checking": 0.9, "speed": 0.8},
     "biases": ["pro_truth", "anti_pr_spin"]},
    {"type": "reddit_conspiracist", "name": "Reddit Conspiracist", "platform": "Reddit", "influence_score": 5.0,
     "description": "A deep-dive researcher who sees patterns everywhere",
     "traits": {"skepticism": 0.95, "conspiracy_minded": 0.8, "research_depth": 0.7},
     "biases": ["anti_corporate", "anti_mainstream", "pro_transparency"]},
    {"type": "reddit_snark", "name": "Reddit Snark", "platform": "Reddit", "influence_score": 3.5,
     "description": "A humorous shitposter who mocks everything",
     "traits": {"humor": 0.95, "snark": 0.95, "creativity": 0.8},
     "biases": ["anti_authority", "pro_memes"]},
    {"type": "reddit_expert", "name": "Reddit Expert", "platform": "Reddit", "influence_score": 6.5,
     "description": "A genuine expert who corrects misinformation",
     "traits": {"expertise": 0.9, "pedantry": 0.8, "skepticism": 0.7},
     "biases": ["pro_accuracy", "anti_hype"]},
    {"type": "tiktok_drama", "name": "TikTok Drama Creator", "platform": "TikTok", "influence_score": 9.0,
     "description": "A drama-focused content creator who sensationalizes",
     "traits": {"sensationalism": 0.95, "speed": 0.9, "emotional_intensity": 0.9},
     "biases": ["pro_drama", "anti_corporate", "pro_entertainment"]},
    {"type": "tiktok_lifestyle", "name": "TikTok Lifestyle Influencer", "platform": "TikTok", "influence_score": 7.0,
     "description": "An aesthetic-focused influencer who cares about brand image",
     "traits": {"brand_sensitivity": 0.8, "aesthetic_focus": 0.9, "loyalty": 0.6},
     "biases": ["pro_aesthetics", "brand_conscious"]},
    {"type": "tech_journalist", "name": "Tech Journalist", "platform": "News Article", "influence_score": 9.0,
     "description": "A professional tech journalist writing for major outlets",
     "traits": {"skepticism": 0.7, "speed": 0.9, "fact_checking": 0.8},
     "biases": ["pro_innovation", "anti_pr_spin", "pro_startup"]},
    {"type": "financial_analyst", "name": "Wall Street Analyst", "platform": "Research Note", "influence_score": 8.5,
     "description": "A financial analyst assessing market impact",
     "traits": {"financial_focus": 0.95, "skepticism": 0.6, "risk_assessment": 0.8},
     "biases": ["pro_shareholder_value", "anti_overvaluation"]},
    {"type": "industry_analyst", "name": "Industry Analyst", "platform": "Industry Report", "influence_score": 8.0,
     "description": "A Gartner-style industry analyst",
     "traits": {"expertise": 0.95, "skepticism": 0.8, "trend_analysis": 0.9},
     "biases": ["pro_market_reality", "anti_hype"]},
    {"type": "competitor", "name": "Competitor PR", "platform": "Statement", "influence_score": 5.0,
     "description": "A competitor's PR team looking for opportunities",
     "traits": {"opportunism": 0.9, "subtlety": 0.7, "brand_protection": 0.9},
     "biases": ["pro_own_brand", "anti_competitor"]},
]
